package com.miteris.cifradocesar

import java.security.NoSuchAlgorithmException
import java.math.BigInteger
import java.security.MessageDigest

class CifradoSHA1 {

    companion object {
        @Throws(NoSuchAlgorithmException::class)
        @JvmStatic
        fun main(args: Array<String>) {
            println("HashCode Generated by SHA-1")
            val s1 = "https://www.miteris.com/"
            println("Entrada: $s1")
            println("Salida: ${encryptThisString(s1)}")
        }

        fun encryptThisString(input: String): String {
            return try {
                val md = MessageDigest.getInstance("SHA-1")
                val messageDigest = md.digest(input.toByteArray())
                val no = BigInteger(1, messageDigest)
                var hashtext = no.toString(16)
                while (hashtext.length < 32) {
                    hashtext = "0$hashtext"
                }
                hashtext
            } catch (e: NoSuchAlgorithmException) {
                throw RuntimeException(e)
            }
        }
    }
}